# Generated by Django 3.2.7 on 2021-10-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='用户id', max_length=128, unique=True, verbose_name='用户id')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=64, null=True, verbose_name='姓名')),
                ('nickname', models.CharField(blank=True, help_text='昵称', max_length=128, null=True, verbose_name='昵称')),
                ('username', models.CharField(blank=True, help_text='用户名', max_length=128, null=True, verbose_name='用户名')),
                ('gender', models.CharField(blank=True, help_text='性别', max_length=8, null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, help_text='出生日期', null=True, verbose_name='出生日期')),
                ('id_card_num', models.CharField(blank=True, help_text='身份证号', max_length=32, null=True, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, help_text='手机号', max_length=16, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, help_text='电子邮箱', max_length=128, null=True, verbose_name='电子邮箱')),
                ('province', models.CharField(blank=True, help_text='省', max_length=32, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, help_text='市', max_length=32, null=True, verbose_name='市')),
                ('avatar', models.CharField(blank=True, help_text='头像', max_length=128, null=True, verbose_name='头像')),
                ('description', models.TextField(blank=True, help_text='描述', null=True, verbose_name='描述')),
                ('is_disable', models.BooleanField(default=False, help_text='是否禁用', verbose_name='是否禁用')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='最近登录时间', verbose_name='最近登录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '聊天用户',
                'verbose_name_plural': '聊天用户',
            },
        ),
        migrations.CreateModel(
            name='SingleChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('have_read', models.BooleanField(default=False, help_text='已读', verbose_name='已读')),
                ('read_time', models.DateTimeField(blank=True, help_text='已读时间', null=True, verbose_name='已读时间')),
                ('content', models.TextField(help_text='内容', verbose_name='内容')),
                ('receiver', models.ForeignKey(help_text='接收者', on_delete=django.db.models.deletion.CASCADE, related_name='single_chat_log_receiver', to='Chat.chatuser', verbose_name='接收者')),
                ('sender', models.ForeignKey(help_text='发送者', on_delete=django.db.models.deletion.CASCADE, related_name='single_chat_log_sender', to='Chat.chatuser', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '单聊聊天记录',
                'verbose_name_plural': '单聊聊天记录',
            },
        ),
    ]
