# Generated by Django 3.2.7 on 2021-10-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_read', models.BooleanField(default=False, help_text='已读', verbose_name='已读')),
                ('read_time', models.DateTimeField(blank=True, help_text='已读时间', null=True, verbose_name='已读时间')),
                ('content', models.TextField(help_text='内容', verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('sender', models.ForeignKey(help_text='发送者', on_delete=django.db.models.deletion.CASCADE, related_name='single_chat_log_sender', to='Chat.chatuser', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '聊天记录',
                'verbose_name_plural': '聊天记录',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='会话名', max_length=128, verbose_name='会话名')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('chat_users', models.ManyToManyField(help_text='会话参与者', to='Chat.ChatUser', verbose_name='会话参与者')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
            },
        ),
        migrations.DeleteModel(
            name='SingleChatLog',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='session',
            field=models.ForeignKey(help_text='聊天会话', on_delete=django.db.models.deletion.CASCADE, to='Chat.session', verbose_name='聊天会话'),
        ),
    ]
