# Generated by Django 3.2.7 on 2021-10-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20211005_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.IntegerField(choices=[(1, '单聊'), (2, '群聊')], default=1, help_text='会话类型', verbose_name='会话类型'),
            preserve_default=False,
        ),
    ]
